/* $Id$ */

/**
 * \file 
 * $Revision$
 * $Date$ 
 * 
 * Copyright (C) 2010 The University of Sydney, Australia
 *
 * This file is part of GPlates.
 *
 * GPlates is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, version 2, as published by
 * the Free Software Foundation.
 *
 * GPlates is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include "LayerTaskTypeInfo.h"


const QString &
GPlatesGui::LayerTaskTypeInfo::get_name(
		GPlatesAppLogic::LayerTaskType::Type layer_type)
{
	static const QString RECONSTRUCTION_NAME = "Reconstruction Tree Generator";
	static const QString RECONSTRUCT_NAME = "Geometry Reconstruction";
	static const QString TOPOLOGY_BOUNDARY_RESOLVER_NAME = "Topological Closed Plate Boundaries Resolver";
	static const QString TOPOLOGY_NETWORK_RESOLVER_NAME = "Topological Networks Resolver";

	static const QString DEFAULT_NAME = "";

	using namespace GPlatesAppLogic::LayerTaskType;

	switch (layer_type)
	{
		case RECONSTRUCTION:
			return RECONSTRUCTION_NAME;

		case RECONSTRUCT:
			return RECONSTRUCT_NAME;

		case TOPOLOGY_BOUNDARY_RESOLVER:
			return TOPOLOGY_BOUNDARY_RESOLVER_NAME;

		case TOPOLOGY_NETWORK_RESOLVER:
			return TOPOLOGY_NETWORK_RESOLVER_NAME;

		default:
			return DEFAULT_NAME;
	}
}


const QString &
GPlatesGui::LayerTaskTypeInfo::get_description(
		GPlatesAppLogic::LayerTaskType::Type layer_type)
{
	static const QString RECONSTRUCTION_DESCRIPTION =
		"A plate-reconstruction hierarchy of total reconstruction poles "
		"which can be used to reconstruct geometries in other layers";

	static const QString RECONSTRUCT_DESCRIPTION =
		"Geometries in this layer will be reconstructed when "
		"this layer is connected to a reconstruction tree layer";

	static const QString TOPOLOGY_BOUNDARY_RESOLVER_DESCRIPTION =
		"Plate boundaries will be dynamically generated by referencing topological section "
		"features, that have been reconstructed to a geological time, and joining them to "
		"form a closed polygon boundary";

	static const QString TOPOLOGY_NETWORK_RESOLVER_DESCRIPTION =
		"Deforming regions will be dynamically formed by referencing topological section "
		"features, that have been reconstructed to a geological time, and triangulating the "
		"convex hull region defined by these reconstructed sections while excluding any "
		"micro-block sections from the triangulation";

	static const QString DEFAULT_DESCRIPTION = "";

	using namespace GPlatesAppLogic::LayerTaskType;

	switch (layer_type)
	{
		case RECONSTRUCTION:
			return RECONSTRUCTION_DESCRIPTION;

		case RECONSTRUCT:
			return RECONSTRUCT_DESCRIPTION;

		case TOPOLOGY_BOUNDARY_RESOLVER:
			return TOPOLOGY_BOUNDARY_RESOLVER_DESCRIPTION;

		case TOPOLOGY_NETWORK_RESOLVER:
			return TOPOLOGY_NETWORK_RESOLVER_DESCRIPTION;

		default:
			return DEFAULT_DESCRIPTION;
	}
}

