# This Makefile is used to compile the file "compilation_test.cc".
# Read the comments at the top of that file for more information about the
# purpose of these two files.

EXTRA_CFLAGS = -Wall -pedantic -ansi -W -Wshadow -Wcast-align -Wwrite-strings -Wfloat-equal -Wno-unused-parameter -Wctor-dtor-privacy -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Werror -gstabs+

SUPPORTING_MATHS_SOURCES = ../maths/PolylineOnSphere.cc ../maths/LatLonPointConversions.cc ../maths/GreatCircleArc.cc ../maths/PointOnSphere.cc ../maths/UnitVector3D.cc ../maths/Vector3D.cc ../maths/PointLiesOnGreatCircleArc.cc ../maths/Real.cc

all:
	g++ ${EXTRA_CFLAGS} compilation_test.cc StringSetSingletons.cc GmlLineString.cc GeoTimeInstant.cc ConstFeatureVisitor.cc GpmlOnePointFiveOutputVisitor.cc XmlOutputInterface.cc ../util/StringSet.cc ../util/UniqueId.cc ${SUPPORTING_MATHS_SOURCES} -I .. -licui18n -licuio

clean:
	rm -f a.out
