package:
  name: pygplates
  version: 0.39

source:
  path: ../../../

build:
  skip: True  # [py<37]
  skip: True  # [win and vc<14]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
  host:
    - pip
    - python
    - numpy
    - cgal-cpp
    - glew
    - libglu          # [linux]
    - xorg-libxfixes  # [linux]
    - qt-main
    - boost
    - libgdal
    - proj
    - qwt
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cgal-cpp
    - gmp        # [unix]
    - mpir       # [win]
    - glew
    - libglu     # [linux]
    - qt-main
    - boost
    - boost-cpp
    - libgdal
    - proj
    - qwt
    - zlib

test:
  imports:
    - pygplates

about:
  home: https://www.gplates.org/
  summary: 'Python library for fine-grained access to GPlates functionality'
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  doc_url: https://www.gplates.org/docs/pygplates/index.html

extra:
  recipe-maintainers:
    - jcannon-gplates
