/* $Id$ */

/**
 * \file 
 * $Revision$
 * $Date$
 * 
 * Copyright (C) 2009, 2010, 2011 The University of Sydney, Australia
 *
 * This file is part of GPlates.
 *
 * GPlates is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, version 2, as published by
 * the Free Software Foundation.
 *
 * GPlates is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef GPLATES_APP_LOGIC_APPLICATIONSTATE_H
#define GPLATES_APP_LOGIC_APPLICATIONSTATE_H

#include <list>
#include <vector>
#include <boost/noncopyable.hpp>
#include <boost/scoped_ptr.hpp>
#include <boost/shared_ptr.hpp>
#include <QObject>

#include "FeatureCollectionFileState.h"
#include "Layer.h"
#include "LayerTaskRegistry.h"
#include "ReconstructGraph.h"
#include "Reconstruction.h"
#include "ReconstructionTree.h"

#include "model/FeatureCollectionHandle.h"
#include "model/ModelInterface.h"
#include "model/types.h"

////////////////////////////////////////////////////////////////////////////////////////////////
// NOTE: Please use forward declarations (and boost::scoped_ptr) instead of including headers
// where possible.
// This header gets included in a lot of other files and we want to reduce compile times.
////////////////////////////////////////////////////////////////////////////////////////////////

namespace GPlatesUtils
{
	class PythonManager;
}

namespace GPlatesAppLogic
{
	class FeatureCollectionFileIO;
	class LayerTask;
	class LayerTaskRegistry;
	class ReconstructGraph;
	class ReconstructMethodRegistry;
	class Serialization;
	class SessionManagement;
	class UserPreferences;


	/**
	 * Stores state that deals with the model and feature collection files.
	 */
	class ApplicationState :
			public QObject,
			private boost::noncopyable
	{
		Q_OBJECT

	public:
		ApplicationState();

		~ApplicationState();

		GPlatesModel::ModelInterface &
		get_model_interface()
		{
			return d_model;
		}

		const double &
		get_current_reconstruction_time() const
		{
			return d_reconstruction_time;
		}

		GPlatesModel::integer_plate_id_type
		get_current_anchored_plate_id() const
		{
			return d_anchored_plate_id;
		}

		/**
		 * Returns the reconstruction generated by the most recent reconstruction.
		 */
		const Reconstruction &
		get_current_reconstruction() const;


		/**
		 * Keeps track of active feature collections loaded from files.
		 */
		FeatureCollectionFileState &
		get_feature_collection_file_state();

		/**
		 * Handling reading/writing feature collection files and notification of read errors.
		 */
		FeatureCollectionFileIO &
		get_feature_collection_file_io();

		/**
		 * Helper for dealing with e.g. boost::serialize
		 */
		GPlatesAppLogic::Serialization &
		get_serialization();

		/**
		 * Stores/Loads loaded file information to and from persistent storage.
		 */
		GPlatesAppLogic::SessionManagement &
		get_session_management();

		/**
		 * Responsible for all persistent GPlates session storage including user preferences.
		 */
		GPlatesAppLogic::UserPreferences &
		get_user_preferences();

		GPlatesUtils::PythonManager&
		get_python_manager()
		{
			return *d_python_manager_ptr;
		}

		/**
		 * Returns the registry of various ways to reconstruct a feature
		 * into @a ReconstructedFeatureGeometry objects.
		 *
		 * This is exposed so that later we can registry user python reconstruct methods.
		 */
		ReconstructMethodRegistry &
		get_reconstruct_method_registry();

		/**
		 * Returns the layer task registry used to create layer tasks.
		 */
		LayerTaskRegistry &
		get_layer_task_registry();

		/**
		 * Returns the reconstruct graph containing the connected layer tasks.
		 *
		 * NOTE: Make sure to call @a reconstruct when you've finished modifying
		 * the returned @a ReconstructGraph.
		 */
		ReconstructGraph &
		get_reconstruct_graph();

		/**
		 * If @a update_default is true, this updates the default reconstruction tree
		 * when the user loads a new rotation file.
		 */
		void
		set_update_default_reconstruction_tree_layer(
				bool update_default = true)
		{
			d_update_default_reconstruction_tree_layer = update_default;
		}

		/**
		 * Returns whether this is updating the default reconstruction tree when the
		 * user loads a new rotation file.
		 */
		bool
		is_updating_default_reconstruction_tree_layer() const
		{
			return d_update_default_reconstruction_tree_layer;
		}

		/**
		 * Suppress the normal auto-creation of layers upon file load in handle_file_state_files_added(),
		 * which would normally be triggered by a call to FeatureCollectionFileIO::load_files().
		 *
		 * This is called from SessionManagement during the loading of a previous Session.
		 */
		void
		suppress_auto_layer_creation(
				bool suppress)
		{
			d_suppress_auto_layer_creation = suppress;
		}


		/**
		 * A convenience class that blocks calls to @a reconstruct and optionally also
		 * calls @a reconstruct when at the scope exit.
		 *
		 * This is useful for clients that are going to call @a reconstruct explicitly but
		 * don't want any unnecessary calls to @a reconstruct to be triggered before then.
		 *
		 * This is currently used by the file loading code to allow loading of multiple
		 * files in one group without causing each file loaded to trigger a separate reconstruction
		 * which can slow loading significantly. Things which trigger the individual loads are
		 * signals emitted when connecting newly created layers.
		 *
		 * These objects can be nested in which case only the destructor of the outermost
		 * scoped object will call @a reconstruct.
		 */
		class ScopedReconstructGuard :
				public boost::noncopyable
		{
		public:
			/**
			 * Constructor blocks calls to @a reconstruct.
			 *
			 * Also optionally calls @a reconstruct on scope exit if @a call_reconstruct_on_scope_exit is true.
			 */
			explicit
			ScopedReconstructGuard(
					ApplicationState &application_state,
					bool reconstruct_on_scope_exit = false) :
				d_application_state(application_state),
				d_call_reconstruct_on_scope_exit(reconstruct_on_scope_exit)
			{
				d_application_state.begin_reconstruct_on_scope_exit();
			}

			/**
			 * Destructor unblocks calls to @a reconstruct but does *not* detect and re-issue
			 * any blocked calls to @a reconstruct.
			 *
			 * But it does call @a reconstruct if 'call_reconstruct_on_scope_exit' was specified in constructor.
			 *
			 * NOTE: Only unblocks when *all* existing @a ScopedReconstructGuard objects go out of scope.
			 */
			~ScopedReconstructGuard()
			{
				d_application_state.end_reconstruct_on_scope_exit(d_call_reconstruct_on_scope_exit);
			}

			/**
			 * Causes @a reconstruct to be called on scope exit (more specifically when *all*
			 * existing @a ScopedReconstructGuard objects go out of scope).
			 *
			 * NOTE: Only one @a ScopedReconstructGuard object out of a nested group of objects
			 * needs to call this for @a reconstruct to be called (when all objects go out of scope).
			 *
			 * It is useful to call this near the end of the scope to avoid @a reconstruct being
			 * called if an exception is thrown (because destructors are called during stack unwind).
			 */
			void
			call_reconstruct_on_scope_exit()
			{
				d_call_reconstruct_on_scope_exit = true;
			}

		private:
			ApplicationState &d_application_state;
			bool d_call_reconstruct_on_scope_exit;
		};

	public slots:
		// NOTE: all signals/slots should use namespace scope for all arguments
		//       otherwise differences between signals and slots will cause Qt
		//       to not be able to connect them at runtime.

		/**
		 * Sets the reconstruction time and if the reconstruction time has changed
		 * performs a new reconstruction and emits the @a reconstruction_time_changed and
		 * @a reconstructed signals.
		 */
		void
		set_reconstruction_time(
				const double &reconstruction_time);

		/**
		 * Sets the anchor plate id and if the anchor plate id has changed
		 * performs a new reconstruction and emits the @a anchor_plate_id_changed and
		 * @a reconstructed signals.
		 */
		void
		set_anchored_plate_id(
				GPlatesModel::integer_plate_id_type anchor_plate_id);

		/**
		 * Performs a reconstruction and emits the @a reconstructed signal.
		 */
		void
		reconstruct();

	signals:
		// NOTE: all signals/slots should use namespace scope for all arguments
		//       otherwise differences between signals and slots will cause Qt
		//       to not be able to connect them at runtime.

		//! Emitted when the reconstruction time has changed.
		void
		reconstruction_time_changed(
				GPlatesAppLogic::ApplicationState &application_state,
				const double &new_reconstruction_time);

		//! Emitted when the anchor plate id has changed.
		void
		anchor_plate_id_changed(
				GPlatesAppLogic::ApplicationState &application_state,
				const GPlatesModel::integer_plate_id_type &new_anchor_plate_id);

		//! Emitted when @a reconstruct called.
		void
		reconstructed(
				GPlatesAppLogic::ApplicationState &application_state);

	private slots:
		// NOTE: all signals/slots should use namespace scope for all arguments
		//       otherwise differences between signals and slots will cause Qt
		//       to not be able to connect them at runtime.

		void
		handle_file_state_files_added(
				GPlatesAppLogic::FeatureCollectionFileState &file_state,
				const std::vector<GPlatesAppLogic::FeatureCollectionFileState::file_reference> &new_files);

		void
		handle_file_state_file_about_to_be_removed(
				GPlatesAppLogic::FeatureCollectionFileState &file_state,
				GPlatesAppLogic::FeatureCollectionFileState::file_reference file);

	private:
		//! The model store.
		GPlatesModel::ModelInterface d_model;

		//
		// NOTE: Most of these are boost::scoped_ptr's to avoid having to include header files.
		//

		/**
		 * Central access point and notification of loaded files.
		 */
		boost::scoped_ptr<FeatureCollectionFileState> d_feature_collection_file_state;

		/**
		 * All file reading/writing goes through here.
		 */
		boost::scoped_ptr<FeatureCollectionFileIO> d_feature_collection_file_io;

		boost::scoped_ptr<Serialization> d_serialization_ptr;
		boost::scoped_ptr<SessionManagement> d_session_management_ptr;

		boost::scoped_ptr<UserPreferences> d_user_preferences_ptr;

		boost::scoped_ptr<GPlatesUtils::PythonManager> d_python_manager_ptr;
		/**
		 * A registry for various ways to reconstruct a feature into @a ReconstructedFeatureGeometry objects.
		 */
		boost::scoped_ptr<ReconstructMethodRegistry> d_reconstruct_method_registry;

		/**
		 * The layer task registry is used to create layer tasks.
		 */
		boost::scoped_ptr<LayerTaskRegistry> d_layer_task_registry;

		/**
		 * The reconstruct graph connects the inputs/outputs of layer tasks to each other and
		 * to input feature collections.
		 *
		 * It also is solely responsible for generating the complete aggregate reconstruction.
		 *
		 * NOTE: This must be declared after @a d_layer_task_registry since it uses it.
		 */
		boost::scoped_ptr<ReconstructGraph> d_reconstruct_graph;
		
		/**
		 * If true, changes the default reconstruction tree layer upon loading a rotation file.
		 */
		bool d_update_default_reconstruction_tree_layer;

		/**
		 * The current reconstruction time.
		 */
		double d_reconstruction_time;

		/**
		 * The current plate id that all reconstruction trees are currently anchored.
		 */
		GPlatesModel::integer_plate_id_type d_anchored_plate_id;

		/**
		 * Reconstruction results are stored here.
		 */
		Reconstruction::non_null_ptr_to_const_type d_reconstruction;

		/**
		 * Keep tracks of the nesting of @a ScopedReconstruct objects.
		 *
		 * When the count reaches zero then @a reconstruct will be called and
		 * subsequent calls to @a reconstruct will no longer be blocked.
		 */
		int d_scoped_reconstruct_nesting_count;

		/**
		 * Used, along with @a d_scoped_reconstruct_nesting_count, to determine if @a reconstruct
		 * should be called when all @a ScopedReconstructGuard objects go out of scope.
		 */
		bool d_reconstruct_on_scope_exit;

		/**
		 * Suppress the normal auto-creation of layers upon file load in handle_file_state_files_added(),
		 * which would normally be triggered by a call to FeatureCollectionFileIO::load_files().
		 */
		bool d_suppress_auto_layer_creation;

		/**
		 * Make signal/slot connections that coordinate the application logic structure
		 * of the application.
		 *
		 * This is a central place to coordinate these connections - a bit like a mediator.
		 */
		void
		mediate_signal_slot_connections();

		//! Begin blocking of calls to @a reconstruct.
		void
		begin_reconstruct_on_scope_exit();

		/**
		 * Ends blocking of calls to @a reconstruct and calls @a reconstruct if the nested
		 * scope count decrements to zero.
		 */
		void
		end_reconstruct_on_scope_exit(
				bool reconstruct_on_scope_exit);

		// Make friend so can call @a begin_reconstruct_on_scope_exit and @a end_reconstruct_on_scope_exit.
		friend class ScopedReconstructGuard;
	};
}

#endif // GPLATES_APP_LOGIC_APPLICATIONSTATE_H
