/* $Id$ */

/**
 * \file 
 * $Revision$
 * $Date$
 * 
 * Copyright (C) 2009 The University of Sydney, Australia
 *
 * This file is part of GPlates.
 *
 * GPlates is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, version 2, as published by
 * the Free Software Foundation.
 *
 * GPlates is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef GPLATES_APP_LOGIC_RECONSTRUCTCONTEXT_H
#define GPLATES_APP_LOGIC_RECONSTRUCTCONTEXT_H

#include <vector>

#include "ReconstructHook.h"

#include "model/ModelInterface.h"
#include "model/FeatureCollectionHandle.h"
#include "model/Reconstruction.h"
#include "model/types.h"


namespace GPlatesAppLogic
{
	class ReconstructContext
	{
	public:
		/**
		 * Constructor has no reconstruction hook.
		 * When @a reconstruct is called just the main reconstruction is performed.
		 */
		explicit
		ReconstructContext(
				GPlatesModel::ModelInterface &model);

		/**
		 * Constructor is the equivalent of above constructor and then @a set_reconstruct_hook.
		 */
		ReconstructContext(
				GPlatesModel::ModelInterface &model,
				ReconstructHook::non_null_ptr_type reconstruct_hook);


		/**
		 * Sets the reconstruct hook that will be called before and after
		 * the reconstruction is generated in @a reconstruct.
		 */
		void
		set_reconstruct_hook(
				ReconstructHook::non_null_ptr_type reconstruct_hook);


		/**
		 * Create a reconstruction for the reconstruction time @a reconstruction_time,
		 * with root @a reconstruction_anchored_plate_id.
		 *
		 * If a @a ReconstructHook has been specified with @a set_reconstruct_hook or
		 * the constructor then it's 'pre_reconstruction_hook' and 'post_reconstruction_hook'
		 * methods are called before and after the reconstruction is created.
		 *
		 * The feature collections in @a reconstruction_features_collection are expected to
		 * contain reconstruction features (ie, total reconstruction sequences and absolute
		 * reference frames).
		 */
		void
		reconstruct(
				const std::vector<GPlatesModel::FeatureCollectionHandle::weak_ref> &
						reconstructable_features_collection,
				const std::vector<GPlatesModel::FeatureCollectionHandle::weak_ref> &
						reconstruction_features_collection,
				const double &reconstruction_time,
				GPlatesModel::integer_plate_id_type reconstruction_anchored_plate_id);


		/**
		 * Returns the reconstruction generated by the most recent call to
		 * @a reconstruct or an empty reconstruction if @a reconstruct has
		 * never been called.
		 */
		GPlatesModel::Reconstruction::non_null_ptr_type
		get_reconstruction()
		{
			return d_current_reconstruction;
		}

	private:
		GPlatesModel::ModelInterface d_model;
		GPlatesModel::Reconstruction::non_null_ptr_type d_current_reconstruction;
		ReconstructHook::maybe_null_ptr_type d_reconstruct_hook;
	};
}

#endif // GPLATES_APP_LOGIC_RECONSTRUCTCONTEXT_H
