/* $Id$ */

/**
 * \file 
 * $Revision$
 * $Date$
 * 
 * Copyright (C) 2011 The University of Sydney, Australia
 *
 * This file is part of GPlates.
 *
 * GPlates is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, version 2, as published by
 * the Free Software Foundation.
 *
 * GPlates is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <boost/optional.hpp>

#include "ReconstructMethodFlowline.h"

#include "FlowlineGeometryPopulator.h"
#include "FlowlineUtils.h"
#include "ReconstructUtils.h"

#include "maths/MultiPointOnSphere.h"
#include "maths/PointOnSphere.h"
#include "maths/PolygonOnSphere.h"
#include "maths/PolylineOnSphere.h"

#include "model/FeatureVisitor.h"
#include "model/types.h"

#include "property-values/GmlLineString.h"
#include "property-values/GmlMultiPoint.h"
#include "property-values/GmlOrientableCurve.h"
#include "property-values/GmlPoint.h"
#include "property-values/GmlPolygon.h"
#include "property-values/GmlTimePeriod.h"
#include "property-values/GpmlConstantValue.h"
#include "property-values/GpmlPlateId.h"


namespace GPlatesAppLogic
{
	namespace
	{
		/**
		 * Finds the present day geometries of a flowline feature.
		 *
		 * Present day geometries probably don't make too much sense for flowlines but
		 * we'll add points and multipoints since they are what is currently used to seed
		 * flowlines.
		 *
		 * FIXME: Currently multiple RFGs map to a single geometry property iterator so even though
		 * we probably only have one present day geometry (the seed point or multipoint) we'll
		 * get multiple RFGs for it. Worst that'll happen is ReconstructContext will map all
		 * RFGs (generated by a flowline feature) to that single present day geometry but this
		 * is ok because the present day geometries are only used by clients interested in RFGs
		 * that have a finite rotation (so they can rotate the present day geometry to get
		 * the reconstructed geometry such as on the graphics card where it's cheaper).
		 * When rendering flowlines the painters will only find reconstructed geometries, which
		 * is fine, and it will paint them directly without rotating them. Also means flowlines
		 * can't be used for reconstructing rasters, etc, but they're not designed for that anyway.
		 */
		class GetPresentDayGeometries :
				public GPlatesModel::FeatureVisitor
		{
		public:
			GetPresentDayGeometries(
					std::vector<ReconstructMethodInterface::Geometry> &present_day_geometries) :
				d_present_day_geometries(present_day_geometries)
			{  }

		private:
			virtual
			void
			visit_gml_multi_point(
					GPlatesPropertyValues::GmlMultiPoint &gml_multi_point)
			{
				d_present_day_geometries.push_back(
						ReconstructMethodInterface::Geometry(
								*current_top_level_propiter(),
								gml_multi_point.multipoint()));
			}

			virtual
			void
			visit_gml_point(
					GPlatesPropertyValues::GmlPoint &gml_point)
			{
				d_present_day_geometries.push_back(
						ReconstructMethodInterface::Geometry(
								*current_top_level_propiter(),
								gml_point.point()));
			}


			std::vector<ReconstructMethodInterface::Geometry> &d_present_day_geometries;
		};
	}
}


bool
GPlatesAppLogic::ReconstructMethodFlowline::can_reconstruct_feature(
		const GPlatesModel::FeatureHandle::const_weak_ref &feature_weak_ref)
{
	FlowlineUtils::DetectFlowlineFeatures visitor;
	visitor.visit_feature(feature_weak_ref);

	return visitor.has_flowline_features();
}


void
GPlatesAppLogic::ReconstructMethodFlowline::get_present_day_geometries(
		std::vector<Geometry> &present_day_geometries,
		const GPlatesModel::FeatureHandle::weak_ref &feature_weak_ref) const
{
	GetPresentDayGeometries visitor(present_day_geometries);

	visitor.visit_feature(feature_weak_ref);
}


void
GPlatesAppLogic::ReconstructMethodFlowline::reconstruct_feature(
		std::vector<ReconstructedFeatureGeometry::non_null_ptr_type> &reconstructed_feature_geometries,
		const GPlatesModel::FeatureHandle::weak_ref &feature_weak_ref,
		const ReconstructParams &/*reconstruct_params*/,
		const ReconstructionTreeCreator &reconstruction_tree_creator,
		const double &reconstruction_time)
{
	FlowlineGeometryPopulator visitor(
			reconstructed_feature_geometries,
			reconstruction_tree_creator,
			reconstruction_time);

	visitor.visit_feature(feature_weak_ref);
}
