#!/bin/sh

DIRS=". .. src ../src"
BINARY=gplates
PROFILE=gmon.out

OPTIONS="--graph --brief --demangle"
# options = --exec-counts

# Find files
binary_path=$BINARY
for dir in $DIRS ; do
	if test -d $dir && test -f $dir/$BINARY ; then
		binary_path=$dir/$BINARY
	fi
done
if ! test -f $binary_path ; then
	echo "*** Can't find 'gplates' binary (searched in $DIRS)"
	exit 1
fi
profile_path=$PROFILE
for dir in $DIRS ; do
	if test -d $dir && test -f $dir/$PROFILE ; then
		profile_path=$dir/$PROFILE
	fi
done
if ! test -f $profile_path ; then
	echo "*** Can't find 'gmon.out' profile data (searched in $DIRS)"
	exit 1
fi

/usr/bin/gprof $OPTIONS $@ $binary_path $profile_path
