if (ICU_INCLUDE_DIR)
	INCLUDE_DIRECTORIES(${SYSTEM_INCLUDE_FLAG} ${ICU_INCLUDE_DIR})

	SET(ICU_LIBRARIES "")

	# Macro for setting up compile flags for ICU modules
	MACRO(ICU_MODULE_SETUP module)
	  IF (ICU_${module}_FOUND)
	    SET(ICU_LIBRARIES ${ICU_LIBRARIES} ${ICU_${module}_LIBRARY})
	  ELSE (ICU_${module}_FOUND)
	    MESSAGE("ICU ${module} library not found.")
	  ENDIF (ICU_${module}_FOUND)
	ENDMACRO(ICU_MODULE_SETUP)

	IF (NOT ICU_DONT_USE_ICU_CORE)
	  ICU_MODULE_SETUP(CORE)
	ENDIF (NOT ICU_DONT_USE_ICU_CORE)

	IF (ICU_USE_I18N)
	  ICU_MODULE_SETUP(I18N)
	ENDIF (ICU_USE_I18N)

	IF (ICU_USE_IO)
	  ICU_MODULE_SETUP(IO)
	ENDIF (ICU_USE_IO)

	IF (ICU_USE_DATA)
	  ICU_MODULE_SETUP(DATA)
	ENDIF (ICU_USE_DATA)

	IF (ICU_USE_LE)
	  ICU_MODULE_SETUP(LE)
	ENDIF (ICU_USE_LE)

	IF (ICU_USE_LX)
	  ICU_MODULE_SETUP(LX)
	ENDIF (ICU_USE_LX)

	IF (ICU_USE_TU)
	  ICU_MODULE_SETUP(TU)
	ENDIF (ICU_USE_TU)
else (ICU_INCLUDE_DIR)
	    MESSAGE("ICU include directory not found - please edit 'ICU_INCLUDE_DIR' entry in CMakeCache.txt file.")
endif (ICU_INCLUDE_DIR)
