"""Resolve the pyGPlates version for scikit-build-core.

This is a dynamic-metadata provider for the '[tool.scikit-build.metadata.version]' table in
'pyproject.toml' (see 'provider' / 'provider-path' there). It exists only because that plugin
protocol is Python: the resolution itself - the release target, the development number counted
from git, and the environment-variable and file fallbacks - lives in CMake, so that the wheel
metadata and the build it configures cannot disagree. See 'cmake/modules/VersionFromGit.cmake'.

It also *records* both product versions into 'cmake/modules/VersionRecorded.cmake'. A pyGPlates
build configures the GPlates version too - 'src/global/Version.cc' is compiled into the module,
and the GPlates version string reaches user data (eg, exported shapefiles carry it) - but only
the pyGPlates version travels in an sdist's PKG-INFO. Without the recorded file, building from
an unpacked sdist, or from the conda-forge feedstock that builds from one, fails at configure
time with no way to supply the missing version. The file ships in the sdist via
'[tool.scikit-build] sdist.include'; it is generated, and .gitignore keeps it uncommitted.

The plugin protocol is scikit-build-core's:

    dynamic_metadata(field: str, settings: Mapping[str, Any] | None) -> str
    get_requires_for_dynamic_metadata(settings) -> list[str]
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

__all__ = ["dynamic_metadata", "get_requires_for_dynamic_metadata"]


def __dir__() -> list[str]:
    return __all__


# '<source>/cmake/gplates_version.py' -> '<source>/cmake/modules/'.
_MODULES_DIR = Path(__file__).resolve().parent / "modules"
_VERSION_SCRIPT = _MODULES_DIR / "VersionFromGit.cmake"
_RECORDED_FILE = _MODULES_DIR / "VersionRecorded.cmake"

# The CMake variable each product's version is spelled as.
_VERSION_VARIABLES = {
    "gplates": "GPLATES_SEMANTIC_VERSION",
    "pygplates": "PYGPLATES_PEP440_VERSION",
}


def _resolve(product: str, cmake: str) -> str:
    """Run the CMake resolver for one product and return the version it prints."""
    process = subprocess.run(  # noqa: S603
        [cmake, "-P", str(_VERSION_SCRIPT), product],
        capture_output=True,
        text=True,
        check=False,
    )
    if process.returncode != 0:
        msg = (
            f"Cannot resolve the {product} version - "
            f"'cmake -P {_VERSION_SCRIPT.name} {product}' failed:\n{process.stderr.strip()}"
        )
        raise RuntimeError(msg)

    # The script echoes the version on its own line; anything on stderr is a CMake warning.
    lines = [line.strip() for line in process.stdout.splitlines() if line.strip()]
    if not lines:
        msg = f"Cannot resolve the {product} version - '{_VERSION_SCRIPT.name}' printed nothing."
        raise RuntimeError(msg)
    return lines[-1]


def _record(versions: dict[str, str]) -> None:
    """Write both versions where a build with no git repository can still find them."""
    body = "".join(
        f"set({_VERSION_VARIABLES[product]} {version})\n"
        for product, version in sorted(versions.items())
    )
    text = (
        "# Generated by 'cmake/gplates_version.py' - do not edit, and do not commit.\n"
        "#\n"
        "# The versions this source tree was packaged with, for a build that has no git\n"
        "# repository to count them from: an unpacked sdist, or the conda-forge feedstock that\n"
        "# builds from one. 'VersionFromGit.cmake' consults git ahead of this file, so it can\n"
        "# never override a working checkout.\n"
        f"{body}"
    )
    try:
        _RECORDED_FILE.write_text(text, encoding="utf-8")
    except OSError as error:
        # Not fatal: every build that can run git resolves the versions for itself. It matters
        # only for the sdist, which would otherwise ship without them - so say so rather than
        # letting that surface much later as a configure failure on someone else's machine.
        print(
            f"WARNING: could not write {_RECORDED_FILE} ({error}). A source distribution built "
            f"now will not carry its versions, and will fail to configure where git is "
            f"unavailable.",
            file=sys.stderr,
        )


def dynamic_metadata(field: str, settings: dict[str, object] | None = None) -> str:
    if field != "version":
        msg = f"Only the 'version' field is supported, not {field!r}"
        raise ValueError(msg)
    if settings:
        msg = "No inline configuration is supported"
        raise ValueError(msg)

    cmake = shutil.which("cmake")
    if cmake is None:
        msg = (
            "Cannot resolve the pyGPlates version: no 'cmake' on PATH. CMake is needed to build "
            "pyGPlates at all, so install it (or let pip install the 'cmake' wheel by building "
            "with build isolation), or set the PYGPLATES_PEP440_VERSION and "
            "GPLATES_SEMANTIC_VERSION environment variables to the versions being built."
        )
        raise RuntimeError(msg)

    versions = {product: _resolve(product, cmake) for product in _VERSION_VARIABLES}
    _record(versions)
    return versions["pygplates"]


def get_requires_for_dynamic_metadata(_settings: dict[str, object] | None = None) -> list[str]:
    # Only when the environment has no CMake of its own - the same way scikit-build-core decides
    # whether to pull in the 'cmake' wheel for the build itself. Asking for it unconditionally
    # would download it even on machines that already have one.
    return [] if shutil.which("cmake") else ["cmake>=3.22"]
